---
- name: Configure keytone service
  hosts: overcloud_controllers
  become: yes
  tasks:
     - name: enable global cache
       lineinfile:
         path: /var/lib/config-data/puppet-generated/keystone/etc/keystone/keystone.conf
         backup: yes
         regexp: ^enabled=False
         line: enabled=true
     - name: modify memservers
       lineinfile:
         path: /var/lib/config-data/puppet-generated/keystone/etc/keystone/keystone.conf
         regexp: memcache_servers *= *192.168.24.*
         line: memcache_servers = localhost:11211
     - name: restart keystone container
       command: podman container restart keystone
