parameter_defaults:
  DeployedNetworkEnvironment:
    net_attributes_map:
      external:
        network:
          dns_domain: external.localdomain.
          mtu: 1500
          name: external
          tags:
          - tripleo_network_name=External
          - tripleo_net_idx=1
          - tripleo_vip=true
        subnets:
          external_subnet:
            cidr: 128.31.20.0/24
            dns_nameservers: []
            gateway_ip: 128.31.20.1
            host_routes: []
            ip_version: 4
            name: external_subnet
            tags:
            - tripleo_vlan_id=3801
      internal_api:
        network:
          dns_domain: internalapi.localdomain.
          mtu: 1500
          name: internal_api
          tags:
          - tripleo_network_name=InternalApi
          - tripleo_net_idx=0
          - tripleo_vip=true
        subnets:
          internal_api_subnet:
            cidr: 172.17.0.0/24
            dns_nameservers: []
            gateway_ip: null
            host_routes: []
            ip_version: 4
            name: internal_api_subnet
            tags:
            - tripleo_vlan_id=208
    net_cidr_map:
      external:
      - 128.31.20.0/24
      internal_api:
      - 172.17.0.0/24
    net_ip_version_map:
      external: 4
      internal_api: 4
resource_registry:
  OS::TripleO::Network: /usr/share/openstack-tripleo-heat-templates/network/deployed_networks.yaml
