parameter_defaults:
  DeployedNetworkEnvironment:
    net_attributes_map:
      external:
        network:
          dns_domain: external.localdomain.
          mtu: 1500
          name: external
          tags:
          - tripleo_vip=true
          - tripleo_net_idx=1
          - tripleo_network_name=External
        subnets:
          external_subnet:
            cidr: 128.31.20.0/24
            dns_nameservers: []
            gateway_ip: 128.31.20.1
            host_routes: []
            ip_version: 4
            name: external_subnet
            tags:
            - tripleo_vlan_id=3801
      internal_api:
        network:
          dns_domain: internalapi.localdomain.
          mtu: 1500
          name: internal_api
          tags:
          - tripleo_vip=true
          - tripleo_net_idx=0
          - tripleo_network_name=InternalApi
        subnets:
          internal_api_subnet:
            cidr: 172.17.1.0/24
            dns_nameservers: []
            gateway_ip: null
            host_routes: []
            ip_version: 4
            name: internal_api_subnet
            tags:
            - tripleo_vlan_id=208
      oc_provisioning:
        network:
          dns_domain: ocprovisioning.localdomain.
          mtu: 1500
          name: oc_provisioning
          tags:
          - tripleo_vip=true
          - tripleo_net_idx=2
          - tripleo_network_name=OcProvisioning
        subnets:
          provisioning_subnet:
            cidr: 192.168.24.0/24
            dns_nameservers: []
            gateway_ip: 192.168.24.254
            host_routes: []
            ip_version: 4
            name: provisioning_subnet
            tags:
            - tripleo_vlan_id=623
    net_cidr_map:
      external:
      - 128.31.20.0/24
      internal_api:
      - 172.17.1.0/24
      oc_provisioning:
      - 192.168.24.0/24
    net_ip_version_map:
      external: 4
      internal_api: 4
      oc_provisioning: 4
resource_registry:
  OS::TripleO::Network: /usr/share/openstack-tripleo-heat-templates/network/deployed_networks.yaml
