---
- name: Copy network scripts and bring up interfaces.
  hosts: overcloud_controllers
  become: yes
  tasks:
     - name: Copy network scripts
       copy: src=ifcfg-eth1 dest=/etc/sysconfig/network-scripts/ifcfg-{{ eth1 }} mode=0644

     - name: Configure public network
       blockinfile:
         path: /etc/sysconfig/network-scripts/ifcfg-{{ eth1 }}
         block: |
           IPADDR={{ public_ip }}
           NAME={{ eth1 }}
           DEVICE={{ eth1 }}

     - name: Bring up public interface
       command: ifup {{ eth1 }}

     - name: Delete default ip route
       command: ip route del default via 192.168.24.1 dev br-ex
