---
- name: Configure ansible switch
  hosts: overcloud_controllers
  become: yes
  tasks:
     - name: Configure mechanism_drivers in ansible_conf.ini
       lineinfile:
         path: /var/lib/config-data/puppet-generated/neutron/etc/neutron/plugins/ml2/ml2_conf.ini
         backup: yes
         regexp: ^(mechanism_drivers).*
         line: mechanism_drivers=ansible,openvswitch,baremetal
     - name: Configure tenant_network_types in ansible_conf.ini
       lineinfile:
         path: /var/lib/config-data/puppet-generated/neutron/etc/neutron/plugins/ml2/ml2_conf.ini
         regexp: ^(tenant_network_types).*
         line: tenant_network_types=vlan
     - name: Get masterauth value from redis.conf
       command: awk '/^masterauth/ {print $2}' /var/lib/config-data/puppet-generated/redis/etc/redis.conf
       register: masterauth_value
     - name: Set [ml2_ansible] and [ansible:switch1] in ansible_conf.ini
       blockinfile:
         path: /var/lib/config-data/puppet-generated/neutron/etc/neutron/plugins/ml2/ml2_conf.ini
         block: "{{ lookup('template', 'switches.j2') }}"
     - name: Restart neutron_api container
       command: podman container restart neutron_api
